config/routes.rb
Rails.application.routes.draw do
  resources :dummies
  resources :attendances
  resources :submitteds
  resources :course_types
  resources :batches, path: '/admin/batches'
  resources :admin_users
  resources :pets
  resources :registrations
  resources :courses
  resources :personal_infos
  get 'sessions/new'

  get '/signup', to: 'users#new'
  resources :users, path: '/students/users'

  resources :users, path: '/students/users' do
    resources :personal_infos
  end
  resources :users, path: '/students/users' do
    resources :registrations
  end
  resources :batches, path: '/admin/batches' do
    resources :courses do
      member do
        get 'delete'
      end
    end
  end


  get 'students/login', to: 'sessions#new'
  post 'students/login', to: 'sessions#create'
  delete 'students/logout', to: 'sessions#destroy'
  root 'sessions#new'
  resources :batches do
    member do
      get 'delete'
    end
  end

  resources :courses do
    member do
      get 'delete'
    end
  end

  resources :batches, path: '/admin/batches' do
    resources :submitteds
  end
  resources :batches, path: '/admin/batches' do
    resources :submitteds do
      resources :attendances do
        end
      end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/submitted.rb
class Submitted < ApplicationRecord
end

app/controllers/submitteds_controller.rb
class SubmittedsController < ApplicationController
  before_action :find_batch
  before_action :find_term

  # GET /submitted_exam_regis_forms
  # GET /submitted_exam_regis_forms.json
  def index
    #@registrations = Registration.where(batches_id: @batch.id, terms_id:@term.id)
    @terms = Term.all
  end

  # GET /submitted_exam_regis_forms/1
  # GET /submitted_exam_regis_forms/1.json
  def show
    @registrations = Registration.where(batches_id: @batch.id, terms_id: params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = Prawn::Document.new
        pdf.text "Joy Roy"
        send_data pdf.render, type: "application/pdf", disposition: "inline"
      end
    end
  end

  # GET /submitted_exam_regis_forms/new
  def new
    @submitted_exam_regis_form = SubmittedExamRegisForm.new
    @attendance = Attendance.new
    @term = Term.new
    @batch = Batch.new
  end

  # GET /submitted_exam_regis_forms/1/edit
  def edit
  end

  # POST /submitted_exam_regis_forms
  # POST /submitted_exam_regis_forms.json
  def create
    @submitted_exam_regis_form = SubmittedExamRegisForm.new(submitted_exam_regis_form_params)

    respond_to do |format|
      if @submitted_exam_regis_form.save
        format.html { redirect_to @submitted_exam_regis_form, notice: 'Submitted exam regis form was successfully created.' }
        format.json { render :show, status: :created, location: @submitted_exam_regis_form }
      else
        format.html { render :new }
        format.json { render json: @submitted_exam_regis_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submitted_exam_regis_forms/1
  # PATCH/PUT /submitted_exam_regis_forms/1.json
  def update
    respond_to do |format|
      if @submitted_exam_regis_form.update(submitted_exam_regis_form_params)
        format.html { redirect_to @submitted_exam_regis_form, notice: 'Submitted exam regis form was successfully updated.' }
        format.json { render :show, status: :ok, location: @submitted_exam_regis_form }
      else
        format.html { render :edit }
        format.json { render json: @submitted_exam_regis_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submitted_exam_regis_forms/1
  # DELETE /submitted_exam_regis_forms/1.json
  def destroy
    @submitted_exam_regis_form.destroy
    respond_to do |format|
      format.html { redirect_to submitted_exam_regis_forms_url, notice: 'Submitted exam regis form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submitted_exam_regis_form
      @submitted_exam_regis_form = SubmittedExamRegisForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submitted_exam_regis_form_params
      params.fetch(:submitted_exam_regis_form, {})
    end
    def find_batch
      if params[:batch_id]
        @batch = Batch.find(params[:batch_id])
      end
    end
    def find_term
      if params[:id]
        @term = Term.find(params[:id])
      end
    end
end

app/helpers/submitteds_helper.rb
module SubmittedsHelper
end

app/views/submitteds/_form.html.erb
<%= simple_form_for(@submitted) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/submitteds/edit.html.erb
<h1>Editing Submitted</h1>

<%= render 'form', submitted: @submitted %>

<%= link_to 'Show', @submitted %> |
<%= link_to 'Back', submitteds_path %>

app/views/submitteds/index.html.erb
<% @page_title = 'Students' %>

<div class="row">
  <div class="col-sm-12">
    <h2>
    <span>Students <small><%= @batch.name %></small></span>
    </h2>
  </div>
</div>

<div id="students"> <!-- for vue wrapper -->

<div class="collapse" id="quickStudentForm">
    <student-form v-on:created="appendCreated"></student-form>
</div>

<div class="row">
  <div >
    <% @terms.each do |term| %>
      <%= link_to "#{term.name} #{"  "}Semester", batch_submitted_path(@batch.id,id:term.id), class: 'btn btn-primary'%>
    <% end%>
  </div>
</div>

</div>

app/views/submitteds/new.html.erb
<h1>New Submitted</h1>

<%= render 'form', submitted: @submitted %>

<%= link_to 'Back', submitteds_path %>

app/views/submitteds/show.html.erb
<% @page_title = 'Students' %>

<div class="row">
  <div class="col-sm-12">
    <h2>
    <span>Students <small><%= @batch.name %></small></span>
    </h2>
  </div>
</div>
<div id="students"> <!-- for vue wrapper -->


<div class="row">
  <div class="col-sm-12">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th data-sortable="true">Registration</th>
          <th data-sortable="true">Name</th>
          <th data-sortable="true">Hall</th>
          <th data-sortable="true">Attendance</th>
          <th data-sortable="true">Actions</th>
        </tr>
      </thead>
    <tbody>
      <% @registrations.each do |registration| %>
      <tr>
        <td><%= registration.users_id %></td>
        <% @user = User.find(registration.users_id)%>
        <%@personal_info = PersonalInfo.find_by(users_id: @user.id)%>
        <td><%= @user.name %></td>
        <% @hall = Hall.find(@personal_info.halls_id) %>
        <td><%= @hall.name %></td>
        <%@attendance = Attendance.find_by(users_id: registration.users_id, terms_id: registration.terms_id, batches_id: registration.batches_id)%>
        <% if !@attendance.nil?%>
        <td><%=@attendance.atten%></td>
        <% else %>
        <td><%=%></td>
        <%end%>
        <%@attendance = Attendance.find_by(users_id: registration.users_id, terms_id: registration.terms_id, batches_id: registration.batches_id)%>
        <%if @attendance.nil?%>
        <td><%= link_to 'Add Attendance', new_batch_submitted_attendance_path(@batch, @term, users_id:registration.users_id), class: 'btn btn-info'%></td>
        <%end%>
        <%if !@attendance.nil?%>
        <td><%= link_to 'Edit Attendance', edit_batch_submitted_attendance_path(@attendance.batches_id,@attendance.terms_id, @attendance.id, users_id:@attendance.users_id), class: 'btn btn-info'%></td>
        <%end%>
      </td>
    </tr>
      <% end%>
    </tbody>
  </table>
  </div>
</div>

</div>