config/routes.rb
Rails.application.routes.draw do
  resources :dummies
  resources :attendances
  resources :submitteds
  resources :course_types
  resources :batches, path: '/admin/batches'
  resources :admin_users
  resources :pets
  resources :registrations
  resources :courses
  resources :personal_infos
  get 'sessions/new'

  get '/signup', to: 'users#new'
  resources :users, path: '/students/users'

  resources :users, path: '/students/users' do
    resources :personal_infos
  end
  resources :users, path: '/students/users' do
    resources :registrations
  end
  resources :batches, path: '/admin/batches' do
    resources :courses do
      member do
        get 'delete'
      end
    end
  end


  get 'students/login', to: 'sessions#new'
  post 'students/login', to: 'sessions#create'
  delete 'students/logout', to: 'sessions#destroy'
  root 'sessions#new'
  resources :batches do
    member do
      get 'delete'
    end
  end

  resources :courses do
    member do
      get 'delete'
    end
  end

  resources :batches, path: '/admin/batches' do
    resources :submitteds
  end
  resources :batches, path: '/admin/batches' do
    resources :submitteds do
      resources :attendances do
        end
      end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :find_batch

  def index
    @courses = @batch.courses
    respond_to do |format|
      format.html
      format.xml
      format.js
      format.json { render json: @courses }
    end
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    store_referrer
    @course = Course.new(code: '', name: '')
  end

  def create
    @course = Course.new(course_params)
    @course.batch = @batch

    if @course.save
      flash[:success] = 'Course Saved Successfully.'
      redirect_to batch_courses_path
    else
      render('new')
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])

    if @course.update_attributes(course_params)
      flash[:success] = 'Course Updated Successfully.'
      redirect_to batch_courses_path
    else
      render('edit', :id => @course.id)
    end
  end

  def delete
    @course = Course.find(params[:id])
  end

  def destroy
    course = Course.find(params[:id])
    if course.destroy
      flash[:success] = 'Course deleted Successfully.'
      redirect_to batch_courses_path
    end
  end

  private
    def apply_filter_if_requested
      @courses = @courses.of_term(params[:term]).includes(:course_type) if params[:term].present?
    end

    def course_params
      # batch_id is exempted from mass assignment, since it is assigned in
      # create action
      params.require(:course).permit(
        :code, :name, :credit,
        :course_type_id, :is_major, :is_optional, :term)
    end

    def find_batch
      if params[:batch_id]
        @batch = Batch.find(params[:batch_id])
      end
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<tr>
  <td><%= course.code %></td>
  <td><%= course.name %></td>
  <%@course_type = CourseType.find(course.course_type_id)%>
  <td><%= @course_type.name %></td>
  <td><%= course.term_ordinal %></td>
  <td><%= course.credit %></td>
  <td class="text-center">
    <%= show_button [course.batch, course] %>
    <%= edit_button [course.batch, course] %>
    <%= link_to fa_icon('trash-o', text: 'Delete'), delete_batch_course_path(@batch, course), class: 'btn btn-xs btn-danger'%>
  </td>
</tr>

app/views/courses/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

  <%= simple_form_for([@batch, @course], inline_errors: false ) do |f| %>
    <%= error_messages_for @course %>

    <%= f.input :code %>
    <%= f.input :name %>

    <div class="form-group">
      <div class="row">
        <div class="col-md-12">
          <%= f.label :course_type_id %>
        </div>
        <div class="col-md-7">
          <%= f.input :course_type_id, collection: CourseType.all, label: false %>
        </div>
        <div class="col-md-5">
          <%= link_to "New Course Type", new_course_type_path,
          class: "btn btn-primary btn-block", remote: true %>
        </div>
      </div>
    </div>
    <%@term = @batch.term_type_id %>
    <%@term = TermType.find(@term) %>
    <%@total_terms = @term.exam_per_year * @batch.total_length_in_year%>

    <%= f.input :term, collection: (1..@total_terms), label_method: :ordinalize %>

    <div class="row">
      <%= f.input :is_major, as: :boolean, label: 'Major?', wrapper_html: { class: 'col-md-6'}  %>
      <%= f.input :is_optional, as: :boolean, label: 'Optional?', wrapper_html: { class: 'col-md-6'}  %>
    </div>

    <%= f.input :credit, as: :integer %>

    <%= f.submit( 'Save Course', class: 'btn btn-success')  %>

  <% end %>
  </div>
</div>

app/views/courses/delete.html.erb
<% @page_title = 'Delete Course' %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2>Delete <%= @course.code %>? </h2>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <p>Are you sure you want to delete the course <%= @course.code %> ?</p>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  
  	<div class="row">
      
    <div class="col-md-3">
      <%= button_to('Yes, Delete', {:action => 'destroy', :id => @course.id }, method: :delete, :class => 'btn btn-danger' ) %>
    </div>

    <div class="col-md-3">
      <%= button_to('No, Don\'t Delete', batch_courses_path, method: :get, class: "btn btn-success") %>
    </div>

    </div>
    
  </div>
</div>

app/views/courses/edit.html.erb
<% @page_title = 'Update Course' %>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2>Update <%= @course.name %></h2>
  </div>
</div>

<div class="modal-form">
  <!-- dynamic modal appear here -->
</div>

<%= render('form') %>

app/views/courses/index.html.erb
<% @page_title = 'Courses' %>

<div class="row">
  <div class="col-sm-12">
    <h2>
	    <span>Courses <small><%= @batch.name %></small>
        <%= form_tag batch_courses_path, method: :get, remote: true, class: "inline form-inline" do %>
				  <%= select_tag(:term, options_for_select((1..@batch.total_terms).map(&:ordinalize), params[:term]), prompt: 'Term', class: "form-control", id: "courses_filter") %>
        <% end %>
				<%= link_to 'Clear Filter', {}, class: "btn btn-primary", id: "clear_filter", remote: true %>
      </span>
	    <%= link_to fa_icon('plus-circle', text: "New Course"), new_batch_course_path(@batch), class: 'pull-right btn btn-primary', id: 'clear_filter' %>
    </h2>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <table class="data-table course-index">
      <thead class="header">
    		<th data-sortable="true">Course Code</th>
    		<th data-sortable="true">Course Name</th>
    		<th data-sortable="true">Course Type</th>
    		<th data-sortable="true">Term</th>
        <th>Credit</th>
    		<th class="filter-false sorter-false">Actions</th>
      </thead>
      <tbody id='course-data'>
        <%= render @courses %>
      </tbody>
    </table>
  </div>
</div>

app/views/courses/index.js.erb
$('table.course-index tbody').html('<%= escape_javascript render(@courses) %>')

app/views/courses/new.html.erb
<% @page_title = 'Add Course' %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2>New Course</h2>
  </div>
</div>

<div class="modal-form">
  <!-- dynamic modal appear here -->
</div>

<%= render('form') %>

app/views/courses/show.html.erb
<% @page_title = 'Course Details' %>

<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <h2>Details of <%= @course.code %>

      <span class="pull-right">
        <%= link_to fa_icon('edit', text: 'Update'),
        edit_batch_course_path(@batch, @course),
        class: "btn btn-info btn-sm" %>

        <%= link_to fa_icon('trash', text: 'Delete'),
        [@batch, @course], method: :delete, data: {confirm: 'Are you sure?'},
        class: "btn btn-danger btn-sm" %>
      </span>

    </h2>
  </div>
</div>


<div class="row">
  <div class="col-md-offset-3 col-md-6">
	<table class="table table-bordered table-striped">
      <tr>
			<td>Course ID</td>
			<td><%= @course.id %></td>
		</tr>
		<tr>
			<td>Batch</td>
			<td>
				<% if @course.batch.present? %>
				<%= @course.batch_name.blank? ? @course.batch_id : @course.batch_name %>
				<% end %>
			</td>
		</tr>
		<tr>
			<td>Course Code</td>
			<td><%= @course.code %></td>
		</tr>
		<tr>
			<td>Name</td>
			<td><%= @course.name %></td>
		</tr>
		<tr>
		<tr>
			<td>Course Type</td>
			<td><%= @course.course_type_id %></td>
		</tr>
		<tr>
			<td>Credit</td>
			<td><%= @course.credit %></td>
		</tr>
		<tr>
			<td>Term</td>
			<td><%= @course.term_ordinal %></td>
		</tr>
		<tr>
			<td>Major?</td>
			<td><%= @course.is_major.humanize %></td>
		<tr>
		<tr>
			<td>Optional?</td>
			<td><%= @course.is_optional.humanize %></td>
		<tr>
	</table>
  </div>
</div>