config/routes.rb
Rails.application.routes.draw do
  resources :dummies
  resources :attendances
  resources :submitteds
  resources :course_types
  resources :batches, path: '/admin/batches'
  resources :admin_users
  resources :pets
  resources :registrations
  resources :courses
  resources :personal_infos
  get 'sessions/new'

  get '/signup', to: 'users#new'
  resources :users, path: '/students/users'

  resources :users, path: '/students/users' do
    resources :personal_infos
  end
  resources :users, path: '/students/users' do
    resources :registrations
  end
  resources :batches, path: '/admin/batches' do
    resources :courses do
      member do
        get 'delete'
      end
    end
  end


  get 'students/login', to: 'sessions#new'
  post 'students/login', to: 'sessions#create'
  delete 'students/logout', to: 'sessions#destroy'
  root 'sessions#new'
  resources :batches do
    member do
      get 'delete'
    end
  end

  resources :courses do
    member do
      get 'delete'
    end
  end

  resources :batches, path: '/admin/batches' do
    resources :submitteds
  end
  resources :batches, path: '/admin/batches' do
    resources :submitteds do
      resources :attendances do
        end
      end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :danger, :info, :success, :warning

  # Store the url trying to be accessed
  def store_location
    session[:desired_url] = request.url if request.get?
  end

  # Store the referrer url
  def store_referrer
    session[:return_to] = request.referrer if request.get?
  end

  # redirect to desired location or default
  def redirect_back_or(default, options = {})
    redirect_to(session.delete(:desired_url) || default, options)
  end

  # redirect to referrer or default
  def return_to_referrer_or(default, options = {})
    redirect_to(session[:return_to] || default, options)
  end

  private

  def confirm_logged_in
    if session[:user_id].present?
      return true
    else
      store_location # store the location of the request
      flash[:danger] = 'Please Log in'
      redirect_to(controller: 'access', action: 'login')
      return false
    end
  end

  def friendly_flash
    flash[:warning] = 'Cannot delete record because dependent record exists'
    redirect_to :back
  end

  def user_not_authorized
    flash[:danger] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

  def authorize_admin!
    unless current_user.admin?
      user_not_authorized
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + "|" + base_title
    end
  end

  def error_messages_for(object)
		render(:partial => 'application/error_messages',
			:locals => {:object => object})
	end

  def ordinalize(number)
    number.ordinalize
  end

  # return the current user if any
  def current_user
    @current_user ||=User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end


  # Returns the method name of the request if any
  def requesting_method
    params['action']
  end


  def extract_error_messages_into_array(query_result)
    messages = []
    query_result.each do |result|
      unless result.errors.empty?
        messages += result.errors.full_messages
      end
    end
    messages
  end

  def set_flash_with_error_messages(errors)
    flash[:warning] = ActionController::Base.helpers.pluralize(errors.count, 'record') + " didn't get saved. <br />"
    flash[:warning] << errors.uniq.join('<br />')
  end

  def prepare_messages_for_flash(query_result)
    non_saved_count = count_faulty_objects(query_result)
    messages = extract_error_messages_into_array(query_result)

    saved_count = query_result.count - non_saved_count

    create_success_flash_message(saved_count) if saved_count > 0
    create_error_flash_message(non_saved_count, messages) unless non_saved_count.zero?
    messages
  end

  def count_faulty_objects(query_result)
    count = 0
    query_result.each { |record| count += 1 if !record.errors.empty? }
    count
  end

  def create_success_flash_message(saved_count)
    flash[:success] = view_context.pluralize(saved_count, 'record') + " saved successfully "
  end

  def create_error_flash_message(count, messages)
    flash[:warning] = view_context.pluralize(count, 'record') + " did't get saved."
  end
end

app/views/application/_breadcrumb.html.erb
<div class="container-fluid">
  <% if logged_in? %>
  <ol class="breadcrumb">
    <% unless %w(login attempt_login logout).include?(params[:action]) %>
    <%#= render_breadcrumbs separator: " &rsaquo; "  %>
    <%= render_breadcrumbs tag: :li, separator: ""  %> <!-- bootstrap style -->
    <% end %>
  </ol>
  <% end %>
</div>

app/views/application/_content_container.html.erb
<div class="container-fluid">
  <%= yield %>
</div>

app/views/application/_error_messages.html.erb
<% if object && object.errors && object.errors.size > 0 %>
	<div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(object.errors.count, "error") %> prohibited this record from being saved:</h3>
    </div>
    <div class="panel-body">
      <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/application/_flash.html.erb
<div class="container-fluid">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %> alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= message.html_safe %>
    </div>
  <% end %>
</div>

app/views/application/_footer.html.erb
<div class="container-fluid">
</div>

app/views/application/_sidebar.html.erb
<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <a class="navmenu-brand" href="/"><i class="fa fa-home fa-fw" aria-hidden="true"></i>&nbsp; Management</a>
    <ul class="nav navmenu-nav">
      <li ><%= link_to fa_icon('users', text: ' Students'), students_login_path %></li>
    </ul>
</div>

app/views/application/_topbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" id = "main">
  <div class="container-fluid">
    <div class="navbar-header" >
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1" onclick="openNav()">
        <span class="sr-only" >Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'University Of Chittagong', root_path, class: 'navbar-brand', id: "logo" %>
      <button type="button" class="pull-right visible-xs navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-right-links" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <!-- .navbar-header -->
    <div class="collapse navbar-collapse" id="navbar-right-links">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <%= link_to raw('<i class="fa fa-user"></i> ' +" #{session[:user_id]} " + '<span class="caret"></span> '), user_path(session[:user_id]), class: 'dropdown-toggle', data: {toggle: 'dropdown'}, role: 'button' %>
            <ul class="dropdown-menu">
              <li><%= link_to fa_icon('wrench', text: " Profile"), user_path(session[:user_id])%></li>
              <li><%= link_to fa_icon('sign-out', text: " Logout"), students_logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to fa_icon('sign-in', text: 'Login'), sessions_new_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>